services:

  node:
    container_name: node
    image: "node:14"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./mycode/index.js:/home/node/app/index.js
    command: sh -c "node index.js"

